[package]
name = "index"
version = "0.1.0"
edition = "2021"

[dependencies]
sa-compression = { git = "https://github.com/unipept/unipept-index.git", rev = "ad9b885636ef646e451f8eb447013880c8c47749" }
sa-index = { git = "https://github.com/unipept/unipept-index.git", rev = "ad9b885636ef646e451f8eb447013880c8c47749" }
sa-mappings = { git = "https://github.com/unipept/unipept-index.git", rev = "ad9b885636ef646e451f8eb447013880c8c47749" }
thiserror = "1.0"
