[package]
name = "index"
version = "0.1.0"
edition = "2021"

[dependencies]
sa-compression = { git = "https://github.com/unipept/unipept-index.git", rev = "a181fa9e3560b838215186faf3f1a9eb80c18cd8" }
sa-index = { git = "https://github.com/unipept/unipept-index.git", rev = "a181fa9e3560b838215186faf3f1a9eb80c18cd8" }
sa-mappings = { git = "https://github.com/unipept/unipept-index.git", rev = "a181fa9e3560b838215186faf3f1a9eb80c18cd8" }
thiserror = "1.0"
