[package]
name = "index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sa-index = { git = "https://github.com/unipept/unipept-index.git", rev = "a181fa9e3560b838215186faf3f1a9eb80c18cd8" }
sa-builder = { git = "https://github.com/unipept/unipept-index.git", rev = "a181fa9e3560b838215186faf3f1a9eb80c18cd8" }
sa-mappings = { git = "https://github.com/unipept/unipept-index.git", rev = "a181fa9e3560b838215186faf3f1a9eb80c18cd8" }
sa-compression = { git = "https://github.com/unipept/unipept-index.git", rev = "a181fa9e3560b838215186faf3f1a9eb80c18cd8" }
serde = "1.0.203"
serde_json = "1.0.117"
rayon = "1.8.1"
datastore = { path = "../datastore" }
thiserror = "1.0"
