[package]
name = "index"
version = "2.3.2"
edition = "2021"

[dependencies]
sa-server = { git = "https://github.com/unipept/unipept-index.git", branch = "feature/add-lightweight-taxa-analyse" }
sa-index  = { git = "https://github.com/unipept/unipept-index.git", branch = "feature/add-lightweight-taxa-analyse" }
thiserror = "1.0"
