[package]
name = "index"
version = "0.1.0"
edition = "2021"

[dependencies]
sa-index = { path = "../sa-index" }
sa-mappings = { path = "../sa-mappings" }
sa-compression = { path = "../sa-compression" }
thiserror = "1.0"
