version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "9:00"
      timezone: Europe/Brussels

  # Maintain dependencies for NPM
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "9:00"
      timezone: Europe/Brussels
