AllCops:
  Exclude:
    - "Gemfile"
    - "Guardfile"
    - "Capfile"
    - "Rakefile"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"
    - "test/**/*"
    - "bin/**/*"
    - "lib/**/*"
    - "node_modules/**/*"

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# disable for now
Layout/LineLength:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
