[package]
name = "database"
version = "2.3.2"
edition = "2021"

[dependencies]
deadpool-diesel = { version = "0.6.1", features = ["mysql"] }
diesel = { version = "2.2.8", features = ["mysql"] }
itertools = "0.13.0"
thiserror = "1.0"
