[package]
name = "database"
version = "2.3.2"
edition = "2021"

[dependencies]
opensearch = "^2.0.0"
itertools = "0.13.0"
thiserror = "1.0"
tokio = { version = "*", features = ["full"] }
url = "2.5.4"
serde = "~1"
serde_json = "~1"
