[package]
name = "unipept-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datastore = { path = "../datastore" }
database = { path = "../database" }
index = { path = "../index" }
axum = { version = "0.7.4", features = ["macros", "form", "multipart"] }
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
clap = { version = "4.5.1", features = ["derive"] }
serde = "1.0.203"
serde_qs = "0.13.0"
serde_json = "1.0.120"
urlencoding = "2.1.3"

sa-index = { path = "../sa-index" }
sa-builder = { path = "../sa-builder" }
sa-mappings = { path = "../sa-mappings" }
sa-compression = { path = "../sa-compression" }
paste = "1.0.15"
thiserror = "1.0"
tower-http = { version = "0.5.2", features = ["cors"] }
