name: Test

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: "test"
      TEST_DATABASE_URL: "mysql2://root:unipept@127.0.0.1:3306/unipept_test"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.9
        env:
          MYSQL_DATABASE: "unipept_test"
          MYSQL_ROOT_PASSWORD: "unipept"
          MYSQL_HOST: "localhost"
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Use ruby from .ruby-version
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bundle exec rails db:test:prepare
          bundle exec rails test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: unipept/unipept-api
