name: Ruby

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: "test"
      DATABASE_URL: "mysql2://root:unipept@127.0.0.1:3306/unipept_test"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.9
        env:
          MYSQL_DATABASE: "unipept_test"
          MYSQL_ROOT_PASSWORD: "unipept"
          MYSQL_HOST: "localhost"
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use ruby from .ruby-version
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        env:
          RAILS_ENV: "test"
        run: |
          bundle exec rails test
